---
collections:
  - name: community.vmware
    version: "6.2.1"

  # community.vmware 6.x bazı ortak modül yardımcılarını
  # vmware.vmware koleksiyonundan kullanır.
  - name: vmware.vmware
    version: "2.9.0"
